version: '3.7'

volumes:
  whitehall-tmp:
  whitehall-node-modules:

x-whitehall: &whitehall
  build:
    context: .
    dockerfile: projects/whitehall/Dockerfile
  image: whitehall
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - whitehall-tmp:/govuk/whitehall/tmp
    - whitehall-node-modules:/govuk/whitehall/node_modules
  working_dir: /govuk/whitehall

services:
  whitehall-lite:
    <<: *whitehall
    depends_on:
      - mysql-5.5
      - redis
    environment:
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
      DATABASE_URL: "mysql2://root:root@mysql-5.5/whitehall_development"
      TEST_DATABASE_URL: "mysql2://root:root@mysql-5.5/whitehall_test"
      REDIS_URL: redis://redis

  whitehall-app: &whitehall-app
    <<: *whitehall
    depends_on:
      - mysql-5.5
      - redis
      - static-app
      - nginx-proxy
      - asset-manager-app
      - publishing-api-app
      - search-api-app
      - content-store-app
    environment:
      DATABASE_URL: "mysql2://root:root@mysql-5.5/whitehall_development"
      REDIS_URL: redis://redis
      VIRTUAL_HOST: whitehall-admin.dev.gov.uk, whitehall-frontend.dev.gov.uk
      BINDING: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart
